server:
    port: 8081
    servlet:
        context-path: /api/v1

spring:
    datasource:
        #url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
        url: jdbc:postgresql://localhost:5432/books_db
        #username: ${POSTGRES_USER}
        username: postgres
        #password: ${POSTGRES_PASSWORD}
        password: postgres
    jpa:
        hibernate:
            show-sql: true
            ddl-auto: validate
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yml
